dist: trusty

language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-7
  - export CXX=g++-7

  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version

  # Run your build commands next
  - cd ClientProject/ClientProject
  - g++ ../../CognitiveVRAnalytics/CognitiveVRAnalytics/*.c* include/googletest/src/gtest-all.cc ClientProject.cpp stdafx.cpp -std=c++11 -I ../../CognitiveVRAnalytics/CognitiveVRAnalytics -I include/curl -I include/googletest -I include/googletest/include -I include/googletest/internal/custom -lcurl -lpthread
  - ./a.out --gtest_output=xml || true
